# Use an official Python runtime as a parent image
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

WORKDIR /app

# Install any needed packages specified in requirements.txt
#COPY ./lib lib -- no libraries used as yet
ADD ./requirements.txt requirements.txt
RUN  pip install -r requirements.txt

COPY ./app app

CMD ["uvicorn", \
     "--host=0.0.0.0", \
     "--port=80", \
     "--reload", \
     "app.main:app" \
]
